### ISSUE TITLE
OleDND issues

### ISSUE THREAD

**Issue by sl1200mk2** [petasis/tkdnd#11]
Hi George,
while compiling tkdnd 2.9 on Windows (msys2 && gcc7.2), there's a lot of warning.
please have a look here:
https://pastebin.com/gApmuZr5

best regards,
nicolas

**Comment by petasis** [comment]
This is interesting. I think the MS compiler gives no warnings. I will look into this.

**Comment by petasis** [comment]
I installed msys2 & gcc 7.2, and compiled with cmake (both win32 and win64). I didn't get these warnings.

**Comment by sl1200mk2** [comment]
can you try with:
./configure
make

**Comment by petasis** [comment]
Yes, with configure I saw the warnings. I have committed a fix. Can you please test and see if warnings are fixed?

**Comment by petasis** [comment]
Just a note: with gcc I am not able to get a working dll (at least one that loads under ActiveTcl 8.6). 
There are some functions undefined.

Using cmake and the free visual 2017 compiler, I get a working dll.

**Comment by sl1200mk2** [comment]
nice George...
https://pastebin.com/Vj3DNrQa

produced dll is working fine here. I use Tcl/Tk that comes with msys2/mingw64:
https://github.com/Alexpux/MINGW-packages/commit/bdca97ff0787857796a7921c36283fd49c688d5e#diff-e8cb6a766a7a5f5200d3e5dadcbbc95f

thank you,
++

**Comment by petasis** [comment]
Well you are right that the dll works. If I run tcl that comes with msys2, the generated dll works. Also, if I run ActiveTcl from within the msys2 terminal, the dll also works. If I run ActiveTcl from outside msys2, the dll cannot be loaded (there are undefined symbols). I think it is a matter of finding the gcc runtime.
