### ISSUE TITLE
Troubles compiling with Msys2 for 64bit

### ISSUE THREAD

**Issue by Lucarda** [petasis/tkdnd#12]
Hi,

I succesfully compile with Msys2 for 32-bit using:

```
./configure
make
```

but when trying for 64-bit `configure` makes a faulty makefile mainly on line 113:

`SHLIB_LD	=  -static-libgcc -static-libstdc++`

but if i replace this line from the 32-bit makefile:

`SHLIB_LD	= ${CC} -shared -static-libgcc -static-libstdc++`

It compiles fine but I have to add the .dll extencion to the resulting "tkdnd29" file.

Also note that the 64-bit makefile has this on line 62:
`PKG_LIB_FILE	= tkdnd2.9`

and the 32-bit makefile this:
`PKG_LIB_FILE	= tkdnd29.dll`

**Comment by petasis** [comment]
I think you are correct. There is a problem in tcl.m4, line 2910. It does not include MINGW64 under "windows".

**Comment by petasis** [comment]
I have added a temporary patch, until a fix in TEA will be made. Can you please verify that it works?

**Comment by Lucarda** [comment]
## It worked perfectly!

Thanxs.

: )
