### ISSUE TITLE
please tkdnd_compat.tcl

### ISSUE THREAD

**Issue by segalion** [petasis/tkdnd#13]
Please remove the '2' character that make tkdnd_compat.tcl unusable.
Most python wrappers uses old tkdnd api (tkdnd_compat).
 
From this:

proc compat::bindsource2 {window type script} {
  ::tkdnd::drag_source register $window $type _**2**_
  bind $window <<DragInitCmd>> "list {copy} %t \[$script\]"
};# compat::bindsource2

Correct with this:

proc compat::bindsource2 {window type script} {
  ::tkdnd::drag_source register $window $type
  bind $window <<DragInitCmd>> "list {copy} %t \[$script\]"
};# compat::bindsource2

**Comment by petasis** [comment]
Dear segalion,

It is a pity that they haven't proceed to version 2 bindings (as I do not test the 1.x compatibility layer often).
In any case, I have committed the change you propose. Can you please verify that it works?

**Comment by petasis** [comment]
Is this bug still open, or has been fixed?

**Comment by segalion** [comment]
sorry. it's ok.
Thanos for your softw
I use old api because of its the only available for python users...
