### ISSUE TITLE
Windows: flickering drag cursor

### ISSUE THREAD

**Issue by flopp** [petasis/tkdnd#17]
Reproduce:
1. Run `demo/basic.tcl` on a windows system
2. Drag from the "Text Drag Source" to the "Drop Target"
3. While hovering over the "Drop Target", the cursor flickers (it apparently changes from the "drag cursor" to the "normal" cursor and vice versa).

Observations:
- The flickering seems to be caused by the `update` call in `olednd::HandleDragOver` - if you comment out this call, the flickering disappears (of course, you also lose any updates needed by Tk, e.g. for updating the text labels; so that's not an option).
- Adding a "delay" to `olednd::HandleDragOver` (something like `set w 0 ; after 200 { incr w }; vwait w`), the flickering becomes more visible.
- If you release the mouse button while the cursor has changed to a "normal" cursor, this mouse event seems to get "eaten", and there's no `Drop` event. The cursor then stays in the "flicker loop" although no mouse button is pressed. This continues until the mouse leaves the drop widget or a button is pressed.

System Information:
I'm using the latest binary distribution of tkdnd from sf.net (`tkdnd2.8-win32-x86_64.tar.gz`), ActiveState TCL 8.6.6, and Windows 10.

I can provide a screen recording showing the flickering if needed.

**Comment by petasis** [comment]
I have provided a solution by changing "update" to "update idletasks".
Can you please test with the current trunk version?

**Comment by flopp** [comment]
The fix works perfectly and eliminates the flickering cursor on my Windows system.
Thank you for your efforts!

**Comment by petasis** [comment]
Ok, I am closing this issue.
