### ISSUE TITLE
'tkInt.h' file not found OSX 10.14

### ISSUE THREAD

**Issue by megrimm** [petasis/tkdnd#22]
Hello,

Just did git pull and now I get:

`./macosx/macdnd.m:22:9: fatal error: 'tkInt.h' file not found`

hmmmm.... 

I re-read last issue on this. updated xcode, etc

tried just ./configure and get:

`checking for Tcl configuration... configure: error: Can't find Tcl configuration definitions. Use --with-tcl to specify a directory containing tclConfig.sh`

Then using:

`bash configure --with-tcl=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tcl.framework --with-tk=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework`

I get:

```
gcc -DPACKAGE_NAME=\"tkdnd\" -DPACKAGE_TARNAME=\"tkdnd\" -DPACKAGE_VERSION=\"2.9\" -DPACKAGE_STRING=\"tkdnd\ 2.9\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DBUILD_tkdnd=/\*\*/ -DMAC_OSX_TK=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DTCL_THREADS=1 -DUSE_TCL_STUBS=1 -DUSE_TCLOO_STUBS=1 -DUSE_TK_STUBS=1 -DMODULE_SCOPE=extern\ __attribute__\(\(__visibility__\(\"hidden\"\)\)\) -DHAVE_HIDDEN=1 -DHAVE_CAST_TO_UNION=1 -DTCL_WIDE_INT_IS_LONG=1 -DUSE_TCL_STUBS=1 -DUSE_TK_STUBS=1 -DMAC_TK_COCOA -std=gnu99 -x objective-c -fobjc-arc -I"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tcl.framework/Headers" -I"/Library/Caches/com.apple.xbs/Sources/tcl/tcl-118.200.2/tk/tk/generic" -I"/Library/Caches/com.apple.xbs/Sources/tcl/tcl-118.200.2/tk/tk/unix" -I""/Library/Caches/com.apple.xbs/Sources/tcl/tcl-118.200.2/tk/tk/xlib"" -I"/Library/Caches/com.apple.xbs/Sources/tcl/tcl-118.200.2/tk/tk/macosx" -iwithsysroot /System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -iwithsysroot /System/Library/Frameworks/Tk.framework/Versions/8.5/PrivateHeaders     -pipe  -Os -DNDEBUG -Wall -fno-common   -c `echo ./macosx/macdnd.m` -o macdnd.o
./macosx/macdnd.m:22:9: fatal error: 'tkInt.h' file not found
#import <tkInt.h>
```

When i do $locate tkInt.h i get:
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tk-private/tkInt.h`

Not sure what changed from last time but wanted to report.

Thanks!
mark

**Comment by petasis** [comment]
Any new info on this?

**Comment by megrimm** [comment]
apologies for slow response time.

here is what i get when running tclsh tcl-conf
```
$ tclsh tcl-conf
TkDND sources: /Users/megrimm/Development/libs/tkdnd
Tcllib's package "fileutil" found!

Cannot find file "tclConfig.sh" within directory (and sub-directories) "/System/Library/Frameworks/Tcl.framework/Versions/8.5".
```

and then configure.

```
$ ./configure
checking TEA configuration... ok (TEA 3.13)
configure: configuring tkdnd 2.9
checking system version... Darwin-18.2.0
checking for Tcl configuration... configure: error: Can't find Tcl configuration definitions. Use --with-tcl to specify a directory containing tclConfig.sh
```

**Comment by petasis** [comment]
I have just tried 10.14 in a VM, and I think that the operating system no longer provides any header files for Tcl at all. This is what "locate tcl.sh" returns:

```
locate tcl.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tcl.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/tcl.h
```
Only inside XCode.

**Comment by petasis** [comment]
Can you please test "tclsh tcl-conf" with the latest commit?

**Comment by petasis** [comment]
To say the truth, supporting OS X is **really** painful. It is not only the issue that it uses non-standard locations, they move header files in arbitrary subdirectories (like tk-private). It is this constant change of the APIs (and the lack of documentation). 10.14 brought new deprecations:

```
warning: 'NSFilenamesPboardType' is deprecated: first deprecated in macOS 10.14 - Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead
warning: 'NSPasteboardTypeFindPanelSearchOptions' is deprecated: first deprecated in macOS 10.14
warning: 'NSStringPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSPostScriptPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSTIFFPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSRTFPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSTabularTextPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSFontPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSRulerPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSColorPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSRTFDPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSHTMLPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSURLPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSPDFPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSVCardPboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSFilesPromisePboardType' is deprecated: first deprecated in macOS 10.14
warning: 'NSMultipleTextSelectionPboardType' is deprecated: first deprecated in macOS 10.14
```
A lot of stuff to be fixed... :D

**Comment by megrimm** [comment]
yeah that worked to configure and build... and yes I get all those depreciation warnings.

bummer this osx stuff is such a pain. thanks for all the work. prob have a couple more macos releases before fully depreciated no?

**Comment by petasis** [comment]
Yes, there are going to be a few releases, but if things go like the previous deprecations, documentation will not exist, and it is going to be a **long** period of trial and error, just to get stuff working again... 

Have you noticed that `configure` arguments are not enough to build TkDND? I had to use a variable to put the additional location of the Tk internal headers :-)

Can we close this issue?

**Comment by megrimm** [comment]
yeah close it. 

fyi we use this with puredata (pd) so maybe at some point the community might be able to pitch in to work on the depreciations.

cheers
mark

**Comment by petasis** [comment]
Well, any help is welcomed :-)
