### ISSUE TITLE
unable to drag from IE

### ISSUE THREAD

**Issue by JamesGKent** [petasis/tkdnd#23]
I'm trying to set up an entry that can accept dragged input, I've tried numerous types and even resorted to setting `*` as the type but text dragged from internet explorer doesn't show the entry as a viable drop target. I'm not sure how far behind the current master my binaries are as they're taken from sourceforge and I can't see a way to relate the two.

**Comment by JamesGKent** [comment]
ok I downloaded and built the source, however I still can't drag content in from IE and i'm not sure where/how to debug this.

**Comment by petasis** [comment]
Yes, I can verify that it does not work. But this is a security feature of Internet explorer, it does not relate to TkDND. You cannot drop in any application, except windows explorer (your desktop, file manager).

In my system, to get drop working also in other applications, I have to go to:

Internet Options -> Security, and unselect the option that relates to protected mode:

![iexplore_2018-11-28_18-57-38](https://user-images.githubusercontent.com/1636393/49168132-8b476000-f33f-11e8-91dc-f7c04810ff80.png)

Uncheck the box just under the slider.

Edge seems to work though out of the box.

**Comment by JamesGKent** [comment]
that's odd, I can drag from IE to word without changing any settings, however you are right, turning off that checkbox does work, as leaving protected mode on and clicking the custom level button, finding the miscellaneous section and enabling the second and third options for dragging of content.

**Comment by petasis** [comment]
Well, in my system the drops are even stranger :-) They drag around huge windows, with either the text drawn, or large renderings of the images. Like OS X (which I don't like).
But in anyway, you can see that IE does in reality sees the drop target (the icon changes from a system one, to a red icon, probably placed by IE), thus it was obvious IE didn't want to drop on this app...

**Comment by JamesGKent** [comment]
your help has been much appreciated, I'm personally using this from python having modified someone else's library to suit my needs, one thing I haven't been able to get working from python is setting up a drag source which is editable using button 1.

for example if I create a text widget and try and register it as a drag source using button 1, when I try and drag a selection into another window it actually keeps changing the selected text, not sure if this is the tk bindings causing an issue or the way pythons tkinter lib is built on top of it. probably the wrong place to ask as this isn't a python library but any ideas what I might be missing?

**Comment by JamesGKent** [comment]
ok so to be clear:
1) yes, I have tried both entry and text
2) yes
3) yes
4) yes
5) yes the selected area moves, not the selected text itself and no drag is started

**Comment by petasis** [comment]
I have created a new package (included in tkdnd) called tkdnd::utils. The idea for this package is to facilitate the process of adding the proper bindings for complex situations like this. It is not yet finished, but you can make a text widget a drag source, and a drop target. (But with the current state of maturity, you cannot do both).

The idea is that you use tkdnd::**text**::drag_source and tkdnd::**text**::drop_target instead of tkdnd::drag_source and tkdnd::drop_target.

I have also added a demo: demos/text_widget_demo.tcl

The main problem with these "large" widgets, is that they already have a (complex) set of predefined bindings...

**Comment by petasis** [comment]
I forgot to mention that I have tested only under Windows...

**Comment by petasis** [comment]
The latest commit supports to drop also on the text widget where the drag was initiated!
I have modified the demo script accordingly. Can you please verify it works in your case (for text widgets)?

Auto-scroll the text widget is still an issue...

**Comment by JamesGKent** [comment]
I have tested this from a tcl shell and can confirm it works as I wanted, i'll need to figure out how to modify my python wrapper to suit now.

Thanks

**Comment by JamesGKent** [comment]
like you say there is already a complex set of bindings, I've been able to modify my wrapper pretty easily although I have some observations:

1. no obvious way to set what happens to text being dragged within a widget, eg if I'm dragging a selection I want it to move to where I drop the cursor, not just copy
2. if a selection is made it can only be cleared by clicking outside the selection, clicking (without drag) within the selection does nothing, not even moving the cursor. this could cause issues if the user selects the entire contents of a widget.

also I can't seem to call this on an entry widget, is this intentional?

**Comment by JamesGKent** [comment]
I can only seem to drag from the text widget once? after that its like the bindings disappear? however its got to be more than that because trying to re bind doesn't fix the issue, I'm trying to see if I can figure out the cause.

**Comment by petasis** [comment]
Yes, you cannot use it with an entry widget, I haven't looked at this at all yet.
Regarding the issues you report, I will see what I can do.
Under what operating system are you testing? Have you played with the new demo?
(In my system, you can drag from the text widget multiple times, and the cursor where the text will be dropped is visible. What version of Tk you are using?)

**Comment by JamesGKent** [comment]
I'm testing under windows 10 1803, I have played with the demo and as stated I can only seem to drag once, I've been unable to figure out why, i'm using the version of tk that ships with python 3.7 which is tk 8.6, I also have activestate's activeTcl installed so I shall try and test with that.

**Comment by JamesGKent** [comment]
ok, so I've tested the demo with activestate's tk and it works as described, i'll keep trying to figure this out

**Comment by petasis** [comment]
Do you think you can share your python wrapper, to have a look?
What python distribution you are using under windows?
(Is it possible I have used something not supported, due to tcl's version used by python?)

**Comment by JamesGKent** [comment]
i'm using python 3.7.1 on 64 bit windows 10, 1803, it reports tk version 8.6.8.
my wrapper (renamed) is attached.
[tkdnd.txt](https://github.com/petasis/tkdnd/files/2663892/tkdnd.txt)

note this wrapper patches the python classes to make the bindings available, a demo (also renamed) is:
[demo_simple_text.txt](https://github.com/petasis/tkdnd/files/2663898/demo_simple_text.txt)

**Comment by petasis** [comment]
Is this bug still open?
