### ISSUE TITLE
Event <<DropEnter>> receives empty event.data when files are dragged over the drop_target

### ISSUE THREAD

**Issue by half-code** [petasis/tkdnd#25]
I am unable to refuse the drop if there are more than 1 files, but i cannot check the length of the files as they are not received when the drop enters the drop target. event.data is filled when the files are dropped.
**Python Source code:**

    from tkinter import *
    from db.tables import ProgramsTable
    from TkinterDnD2 import *
    class InputDialog(object):
    
        def __init__(self, master):
            top = self.top = Toplevel(master)
            self.dndLabel = Label(top, text="Drag and drop file to fill info.")
            self.dndLabel.configure(font=("Helvetica", 15, "bold"))
            self.label = Label(top, text="Enter file name")
            self.entry = Entry(top)
            self.label1 = Label(top, text="Enter file path")
            self.entry1 = Entry(top)
            self.dndLabel.grid(row=0, columnspan=2, padx=10, pady=5)
            self.label.grid(row=1, column=0, padx=10, pady=5)
            self.entry.grid(row=1, column=1, padx=10, pady=5)
            self.label1.grid(row=2, column=0, padx=10, pady=5)
            self.entry1.grid(row=2, column=1, padx=10, pady=5)
            self.button = Button(top, text='Save', command=self.cleanup)
            self.button.grid(row=4, columnspan=2, padx=10, pady=5)
            self.init_dnd()
    
        def cleanup(self):
            self.value1 = self.entry.get()
            self.value2 = self.entry1.get()
            self.top.destroy()
    
        def init_dnd(self):
            self.top.drop_target_register(DND_FILES)
            self.top.dnd_bind("<<DropEnter>>", self.drop_enter)
            self.top.dnd_bind("<<Drop>>", self.file_dropped)
    
        def file_dropped(self, event):
            print(event.data)
            return COPY
    
        def drop_enter(self, event):
            no_of_files = self.top.tk.splitlist(event.data)
            print('\nAction:', event.action)
            print('Supported actions:', event.actions)
            print('Mouse button:', event.button)
            print('Type codes:', event.codes)
            print('Current type code:', event.code)
            print('Common source types:', event.commonsourcetypes)
            print('Common target types:', event.commontargettypes)
            print('Data:', event.data)
            print('Event name:', event.name)
            print('Supported types:', event.types)
            print('Modifier keys:', event.modifiers)
            print('Supported source types:', event.supportedsourcetypes)
            print('Operation type:', event.type)
            print('Source types:', event.sourcetypes)
            print('Supported target types:', event.supportedtargettypes)
            print('Widget:', event.widget, '(type: %s)' % type(event.widget))
            print('X:', event.x_root)
            print('Y:', event.y_root, '\n')
            if len(no_of_files) > 1:
                return REFUSE_DROP
    
    root = TkinterDnD.Tk()
    app = InputDialog(master=root)
    root.mainloop()
    
**Output for the print statements:**

> Action: copy
Supported actions: ('copy', 'move', 'link')
Mouse button: 1
Type codes: ('0x0000c115', '0x0000c233', '0x0000c230', '0x0000c124', '0x0000c234', '0x0000c123', '0x0000000f', '0x0000c006', '0x0000c0df', '0x0000c007', '0x0000c119')
Current type code: 0x0000c115
Common source types: ('CF_HDROP',)
Common target types: ('CF_HDROP',)
Data: 
Event name: <<DropEnter>>
Supported types: ('{Shell IDList Array} UsingDefaultDragImage DragImageBits DragContext DragSourceHelperFlags InShellDragLoop CF_HDROP FileName FileContents FileNameW FileGroupDescriptorW',)
Modifier keys: ('1',)
Supported source types: ('{Shell IDList Array} UsingDefaultDragImage DragImageBits DragContext DragSourceHelperFlags InShellDragLoop CF_HDROP FileName FileContents FileNameW FileGroupDescriptorW',)
Operation type: CF_HDROP
Source types: ('{Shell IDList Array} UsingDefaultDragImage DragImageBits DragContext DragSourceHelperFlags InShellDragLoop CF_HDROP FileName FileContents FileNameW FileGroupDescriptorW',)
Supported target types: ('',)
Widget: .dnd_demo_listbox (type: <class 'tkinter.Listbox'>)
X: 480
Y: 355

**Comment by petasis** [comment]
I have installed python3, is there a package for installing tkdnd?

**Comment by petasis** [comment]
Ok, I installed it manually.

**Comment by petasis** [comment]
I have added a fix at the master branch, and I have created a new release (tkdnd-release-test-v2.9.1).
Can you please test it works in your case?
Please not that the fix works only under Windows.

**Comment by half-code** [comment]
> I have added a fix at the master branch, and I have created a new release (tkdnd-release-test-v2.9.1).
> Can you please test it works in your case?
> Please not that the fix works only under Windows.

Okay i will try this and let you know.

**Comment by half-code** [comment]
> I have added a fix at the master branch, and I have created a new release (tkdnd-release-test-v2.9.1).
> Can you please test it works in your case?
> Please not that the fix works only under Windows.

Yes it works , Now thank you
