### ISSUE TITLE
mutually exclusive flags in CMakeLists.txt?

### ISSUE THREAD

**Issue by chrstphrchvz** [petasis/tkdnd#26]
https://github.com/petasis/tkdnd/blob/86eb1d7096b3d7e7ca39332d48a29e5b8102dc9d/CMakeLists.txt#L77-L78

Are these lines mutually exclusive, such that `-fno-objc-arc` is ignored? Should `-fno-objc-arc` be removed?

Cc @radarhere (author of #4)

**Comment by radarhere** [comment]
https://clang.llvm.org/docs/AutomaticReferenceCounting.html

> ARC may be explicitly enabled with the compiler flag -fobjc-arc. It may also be explicitly disabled with the compiler flag -fno-objc-arc. The last of these two flags appearing on the compile line “wins”.

So yes, I would agree with your suggestion that the first one could be removed.

**Comment by chrstphrchvz** [comment]
> https://clang.llvm.org/docs/AutomaticReferenceCounting.html
> 
> > ARC may be explicitly enabled with the compiler flag -fobjc-arc. It may also be explicitly disabled with the compiler flag -fno-objc-arc. The last of these two flags appearing on the compile line “wins”.
> 
> So yes, I would agree with your suggestion that the first one could be removed.

Thanks for finding that.

I have opened a PR to remove the old flag: #28
