### ISSUE TITLE
libtkdnd2.9.so: undefined symbol: XSendEvent (Ubuntu 18.04)

### ISSUE THREAD

**Issue by segalion** [petasis/tkdnd#27]
I was trying tkdnd2.9 from your releases for linux64, and when _require package it says:

libtkdnd2.9.so: undefined symbol: XSendEvent

Do you know if there is needed some aditional .deb ?

Thanks again.

**Comment by chrstphrchvz** [comment]
I can reproduce this using Tk 8.6 as packaged by Ubuntu 18.10. However I can only reproduce from `tclsh` and not with `wish`.

My guess of what's wrong is that tkdnd is not being linked to X11. When I configure tkdnd with `LDFLAGS=-L/usr/X11/lib LIBS=-lX11`, tkdnd works as expected from `tclsh`.

**Comment by segalion** [comment]
I dont understand very well where is the problem: 
- (1) in Ubuntu 18.10 tk 8.6 package?
- (2) in tkdnd linux build?

**Comment by chrstphrchvz** [comment]
> I dont understand very well where is the problem:
> 
> * (1) in Ubuntu 18.10 tk 8.6 package?
> * (2) in tkdnd linux build?

Based on what I tried, I think the problem may be in either TkDND binary from Travis, and/or in the configure script. I'm not certain the Ubuntu-provided Tk 8.6 is not posing the problem though, as I have not tried using a self-compiled Tk.

**Comment by petasis** [comment]
I think the problem is that TkDND does not link to the X11 library. This is because it assumes it is loaded in an X11 application (like wish). I would expect that "package require Tk" will fix this even for tclsh, but probably it doesn't.

I have made a fix in configure.ac that will include lib X11 during linking, I hope it will solve the problem.

**Comment by petasis** [comment]
Can you please test if the binaries of the latest release (2.9.2) work?

https://github.com/petasis/tkdnd/releases

**Comment by segalion** [comment]
I can confirm that 2.9.2 with Ubuntu 18.10 works like a charm!!!
Thanks again, Petasis

I have seen that event.modifiers ('%m') is reported now as ('%m',) in linux.
In windows is reported as i.e: ('ctrl shift 1',) if ctrl+shift+ button1 is pressed when dragging
But I think is similar behaviour in previous tkdnd versions

**Comment by petasis** [comment]
I am not sure I understood what is the problem with %m. There is a comma that has been erroneously included? The comma is not indented, there must be a typo somewhere in the tkdnd tcl library.

**Comment by petasis** [comment]
I cannot see the extra comma in linux. In fact, I see that only the pressed button is reported in linux :-)
Are you testing through python?

**Comment by petasis** [comment]
Is this bug still open?
