### ISSUE TITLE
Bad binding substitution of `%b` and `%m` (at least on Unix)

### ISSUE THREAD

**Issue by flopp** [petasis/tkdnd#35]
The documentation says that `%b` is replaced by the mouse button that is pressed during the drag/drop operation, and `%m` is replaced by the pressed modifier keys; but in the code (`tkdnd_generic.tcl`), both are replaced by `$_pressedkeys`:

```
set cmd [string map [list ... \
  ...
  %b \{$_pressedkeys\} %m \{$_pressedkeys\} \
  ...
  ] $cmd]
```

At least on Unix, `_pressedkeys` seems to be constantly set to `1` (`tkdnd_unix.tcl`:67 => `set _pressedkeys 1`).

=> Something's wrong here...

**Comment by petasis** [comment]
Yes, this does not has an easy answer. The documentation has to change.

**Comment by petasis** [comment]
I have provided a fix for this bug. But you have to take into consideration this (taken from the Changelog):

Under Unix, the drop target is not supposed to decide on the action: it is the drag source that takes this decision. The drop target must either accept the action provided by the drag source, or replay with 	"copy" or "ask". This must be reflected in the documentation.

**Comment by petasis** [comment]
I have updated also the documentation.

**Comment by flopp** [comment]
Ok, thanks.
