### ISSUE TITLE
it does not work ok on windows 10

### ISSUE THREAD

**Issue by noval102200** [petasis/tkdnd#37]
I have use tkdnd x64 and x86 version both on windows 10.but it doest not work ok.
the x86 version work ok on windows7.

**Comment by petasis** [comment]
TkDND runs under all versions of Windows I think. It runs in my Windows 10 pc:

![explorer_2019-07-19_22-04-05](https://user-images.githubusercontent.com/1636393/61558971-304eae80-aa71-11e9-878e-f300c182b092.png)

What is the error you are getting?
