### ISSUE TITLE
nmake install failure when building tkdnd2.9.2 on Windows 7 64-bit

### ISSUE THREAD

**Issue by Heikedin** [petasis/tkdnd#38]
Hello to anybody that is reading my issue.

I've tried to build TkDND using CMake on Windows according to steps from [this page.](https://github.com/petasis/tkdnd) I believe that I've met all the requirements needed to build it. However, I was unable to successfully build it because the final step didn't work correctly:
`nmake install`

Here is a log of what I've achieved while building:

> **********************************************************************
> ** Visual Studio 2017 Developer Command Prompt v15.9.16
> ** Copyright (c) 2017 Microsoft Corporation
> **********************************************************************
> 
> C:\Windows\System32>CD /D C:\Users\Admin\Desktop\HICES\tkdnd-master/cmake
> 
> C:\Users\Admin\Desktop\HICES\tkdnd-master\cmake>build64.bat
> -- The C compiler identification is MSVC 19.16.27034.0
> -- The CXX compiler identification is MSVC 19.16.27034.0
> -- Check for working C compiler: H:/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hos
> tx86/x86/cl.exe
> -- Check for working C compiler: H:/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hos
> tx86/x86/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: H:/Enterprise/VC/Tools/MSVC/14.16.27023/bin/H
> ostx86/x86/cl.exe
> -- Check for working CXX compiler: H:/Enterprise/VC/Tools/MSVC/14.16.27023/bin/H
> ostx86/x86/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- TKDND version: 2.9.2
> -- Looking for include file Strsafe.h
> -- Looking for include file Strsafe.h - found
> -- ===========================================================
> --  Welcome to the tkdnd 2.9.2 build system!
> --   * Selected generator:  NMake Makefiles
> --   * Operating System ID: Windows-6.1.7601-AMD64
> --   * Installation Directory: C:/Users/Admin/Desktop/HICES/tkdnd-master/cmake/r
> untime
> -- ===========================================================
> -- Searching for Tcl/Tk...
> -- Found Tclsh: C:/ActiveTcl/bin/tclsh.exe (found version "8.6")
> -- Found TCL: C:/ActiveTcl/lib/tcl86t.lib
> -- Found TCLTK: C:/ActiveTcl/lib/tcl86t.lib
> -- Found TK: C:/ActiveTcl/lib/tk86t.lib
> --   TCL_TCLSH:               C:/ActiveTcl/bin/tclsh.exe
> --   TCL_INCLUDE_PATH:        C:/ActiveTcl/include
> --   TCL_STUB_LIBRARY:        C:/ActiveTcl/lib/tclstub86.lib
> --   TCL_LIBRARY:             C:/ActiveTcl/lib/tcl86t.lib
> --   TK_WISH:                 C:/ActiveTcl/bin/wish.exe
> --   TK_INCLUDE_PATH:         C:/ActiveTcl/include
> --   TK_STUB_LIBRARY:         C:/ActiveTcl/lib/tkstub86.lib
> --   TK_LIBRARY:              C:/ActiveTcl/lib/tk86t.lib
> --       + Shared Library: tkdnd
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/Admin/Desktop/HICES/tkdnd-master/c
> make/debug-nmake-x86_64
> -- The C compiler identification is MSVC 19.16.27034.0
> -- The CXX compiler identification is MSVC 19.16.27034.0
> -- Check for working C compiler: H:/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hos
> tx86/x86/cl.exe
> -- Check for working C compiler: H:/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hos
> tx86/x86/cl.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: H:/Enterprise/VC/Tools/MSVC/14.16.27023/bin/H
> ostx86/x86/cl.exe
> -- Check for working CXX compiler: H:/Enterprise/VC/Tools/MSVC/14.16.27023/bin/H
> ostx86/x86/cl.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- TKDND version: 2.9.2
> -- Looking for include file Strsafe.h
> -- Looking for include file Strsafe.h - found
> -- ===========================================================
> --  Welcome to the tkdnd 2.9.2 build system!
> --   * Selected generator:  NMake Makefiles
> --   * Operating System ID: Windows-6.1.7601-AMD64
> --   * Installation Directory: C:/Users/Admin/Desktop/HICES/tkdnd-master/cmake/r
> untime
> -- ===========================================================
> -- Searching for Tcl/Tk...
> -- Found Tclsh: C:/ActiveTcl/bin/tclsh.exe (found version "8.6")
> -- Found TCL: C:/ActiveTcl/lib/tcl86t.lib
> -- Found TCLTK: C:/ActiveTcl/lib/tcl86t.lib
> -- Found TK: C:/ActiveTcl/lib/tk86t.lib
> --   TCL_TCLSH:               C:/ActiveTcl/bin/tclsh.exe
> --   TCL_INCLUDE_PATH:        C:/ActiveTcl/include
> --   TCL_STUB_LIBRARY:        C:/ActiveTcl/lib/tclstub86.lib
> --   TCL_LIBRARY:             C:/ActiveTcl/lib/tcl86t.lib
> --   TK_WISH:                 C:/ActiveTcl/bin/wish.exe
> --   TK_INCLUDE_PATH:         C:/ActiveTcl/include
> --   TK_STUB_LIBRARY:         C:/ActiveTcl/lib/tkstub86.lib
> --   TK_LIBRARY:              C:/ActiveTcl/lib/tk86t.lib
> --       + Shared Library: tkdnd
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Users/Admin/Desktop/HICES/tkdnd-master/c
> make/release-nmake-x86_64
> 
> C:\Users\Admin\Desktop\HICES\tkdnd-master\cmake>cd release-nmake-x86_64
> 
> C:\Users\Admin\Desktop\HICES\tkdnd-master\cmake\release-nmake-x86_64>nmake insta
> ll
> 
> Microsoft (R) Program Maintenance Utility Version 14.16.27034.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> Scanning dependencies of target tkdnd2.9.2
> [ 50%] Building CXX object CMakeFiles/tkdnd2.9.2.dir/win/TkDND_OleDND.cpp.obj
> TkDND_OleDND.cpp
> [100%] Linking CXX shared library libtkdnd2.9.2.dll
> LINK: command "H:\Enterprise\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\link.exe
> /nologo @CMakeFiles\tkdnd2.9.2.dir\objects1.rsp /out:libtkdnd2.9.2.dll /implib:t
> kdnd2.9.2.lib /pdb:C:\Users\Admin\Desktop\HICES\tkdnd-master\cmake\release-nmake
> -x86_64\libtkdnd2.9.2.pdb /dll /version:0.0 /machine:X86 /nodefaultlib:MSVCRT.LI
> B /INCREMENTAL:NO LIBCMT.LIB C:\ActiveTcl\lib\tclstub86.lib C:\ActiveTcl\lib\tks
> tub86.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib o
> leaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:libtkdnd2
> .9.2.dll.manifest" failed (exit code 1120) with the following output:
>    Creating library tkdnd2.9.2.lib and object tkdnd2.9.2.exp
> TkDND_OleDND.cpp.obj : error LNK2019: unresolved external symbol _Tcl_InitStubs
> referenced in function _Tkdnd_Init
> TkDND_OleDND.cpp.obj : error LNK2019: unresolved external symbol _Tk_InitStubs r
> eferenced in function _Tkdnd_Init
> TkDND_OleDND.cpp.obj : error LNK2019: unresolved external symbol _tclStubsPtr re
> ferenced in function "public: virtual __thiscall TkDND_DropTarget::~TkDND_DropTa
> rget(void)" (??1TkDND_DropTarget@@UAE@XZ)
> TkDND_OleDND.cpp.obj : error LNK2019: unresolved external symbol _tkStubsPtr ref
> erenced in function "int __cdecl TkDND_RegisterDragDropObjCmd(void *,struct Tcl_
> Interp *,int,struct Tcl_Obj * const * const)" (?TkDND_RegisterDragDropObjCmd@@YA
> HPAXPAUTcl_Interp@@HQBQAUTcl_Obj@@@Z)
> TkDND_OleDND.cpp.obj : error LNK2019: unresolved external symbol _tkPlatStubsPtr
>  referenced in function "void __cdecl TkDND_OnWindowDestroy(void *,union _XEvent
>  *)" (?TkDND_OnWindowDestroy@@YAXPAXPAT_XEvent@@@Z)
> libtkdnd2.9.2.dll : fatal error LNK1120: 5 unresolved externals
> NMAKE : fatal error U1077: 'C:\Users\Admin\AppData\Local\Programs\Python\Python3
> 7-32\Lib\site-packages\cmake\data\bin\cmake.exe' : return code '0xffffffff'
> Stop.
> NMAKE : fatal error U1077: 'H:\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\
> x86\nmake.exe' : return code '0x2'
> Stop.
> NMAKE : fatal error U1077: 'H:\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX86\
> x86\nmake.exe' : return code '0x2'
> Stop.

What could be causing the problem? Is linker not working properly? Is there an easy way to fix it? If there is more information needed to resolve the problem, please tell me what should I provide.

Thanks for reading my issue and cheers!

**Comment by petasis** [comment]
My first reaction is that we provide pre-build binaries in the releases section. I will have to look into this more thoroughly.

**Comment by Heikedin** [comment]
[tkdnd-master.zip](https://github.com/petasis/tkdnd/files/3726343/tkdnd-master.zip) is what I've tried to build.
[release-nmake-x86_64.zip](https://github.com/petasis/tkdnd/files/3726345/release-nmake-x86_64.zip) is the release version I've been able to get after running build64.bat

Have I missed anything/understood what you needed correctly?

I'm really grateful for taking interest in my issue! Please take your time.

**Comment by petasis** [comment]
I really cannot understand. The Tcl stub libs are included in the build, and all the missing symbols are from these libs. Can you build any other extension?
Have you started the correct command prompt for the type you want to compile for? (x86, x64)?

**Comment by petasis** [comment]
Is you activetcl matching the architecture you want to build for?

**Comment by Heikedin** [comment]
I'm not gonna lie, I'm a bit new in building so I have no idea which extension would be easy to check if it builds properly.

But I've tried to build both x86 and x64 versions from the start in separate folders - the result was the same I believe, very similar errors.

I've checked executables in ActiveTcl and there are for example multiple versions of one like: tclsh.exe, tclsh86t.exe, tclsht.exe - does it mean that it supports multiple architectures then? I've downloaded [from this page](https://www.activestate.com/products/activetcl/downloads/) version 8.6.

**Comment by petasis** [comment]
When you installed Visual Studio, there are two command prompt links added to your programs. Something like "x64 Native Tools Command Prompt for VS 2019" and "x86 Native Tools Command Prompt for VS 2019". You have to run the correct command (one of the two) for the architecture you want to build (x64 or x32), and then run cmake in there.

Else, it will not work at all. As in your case. CMake cannot fix your build chain, you have to set up it before starting the tkdnd build process.
