### ISSUE TITLE
Platform independent types

### ISSUE THREAD

**Issue by E-Paine** [petasis/tkdnd#43]
When calling the `platform_independent_types` method, I get the following error:

`invalid command name "::tkdnd::generic::platform_independent_types"`

The fix, I believe, is changing line 542 of `tkdnd_generic` from:

 `proc ::tkdnd::platform_independent_types { types } {`

to:

`proc generic::platform_independent_types { types } {`

Thanks

**Comment by E-Paine** [comment]
@petasis, I really don't mind if you don't merge the PR but I would like to know that this fix is the correct one so I can apply it to [our proposed Windows binaries for CPython](https://github.com/E-Paine/cpython-bin-deps/tree/tkdnd-bin). Also, do you know when the next release is due (so we can work out if it is worth waiting for before merging)?

**Comment by petasis** [comment]
Fixed.
