### ISSUE TITLE
Error on 'entier' in SetPressedKeys

### ISSUE THREAD

**Issue by rjkg** [petasis/tkdnd#44]
MacOS Sierra, Tcl 8.5.9 
Demo 'simple_target.tcl' failed with error on generic::SetPressedKeys  - 'entier'  

bad class "entier": must be alnum, alpha, ascii, control, boolean, digit, double, false, graph, integer, list, lower, print, punct, space, true, upper, wideinteger, wordchar, or xdigit

if {[string is entier -strict $b]} {....

Replacing 'entier' with 'integer' appears to have fixed the problem.

**Comment by flopp** [comment]
`string is entier ...` has been added to Tcl in 8.6.0 (https://core.tcl-lang.org/tips/doc/trunk/tip/395.md)

**Comment by petasis** [comment]
Fixed.
