### ISSUE TITLE
Tk 8.3 does not have [tk windowingsystem]

### ISSUE THREAD

**Issue by chrstphrchvz** [petasis/tkdnd#59]
TkDND currently documents 8.3.3 as the minimum supported version, but it relies on `[tk windowingsystem]` which requires Tk 8.4.0. Should documentation raise the supported version, or does TkDND intend to continue supporting 8.3?

Personally, I have only tested TkDND with 8.6 and have not yet noticed incompatibilities with 8.4 or 8.5.

**Comment by petasis** [comment]
Well, in the past it make sense. Is anybody using Tk 8.3.3 nowadays?

Perhaps we should drop support for 8.3 & 8.4, and start with 8.5. I see the apple part already asks for 8.5.
I cannot remember why...

**Comment by petasis** [comment]
Ok, I have changed the minimum Tk version to 8.4.

**Comment by chrstphrchvz** [comment]
> I see the apple part already asks for 8.5.
> I cannot remember why...

The Cocoa port of Tk Aqua, which replaced the Carbon port, only existed for 8.5 and later. The TkDND code for Tk Aqua has only ever used Cocoa, so it would not have worked with 8.4.
