### ISSUE TITLE
Tcl9 version of tkdnd

### ISSUE THREAD

**Issue by PaulObermeier** [petasis/tkdnd#60]
Hi Georgios,

please find attached a version of tkdnd, which works both with Tcl 8.6 as well as Tcl 9.0.b1.
It would be nice, if you could merge the needed changes into the official repository version.

Best regards,
Paul

[tkdnd-2.9.4.zip](https://github.com/petasis/tkdnd/files/13678187/tkdnd-2.9.4.zip)

**Comment by petasis** [comment]
Why you have named it 2.9.4? Shouldn't it be 2.9.3?

**Comment by petasis** [comment]
I don't remember why version 2.9.3 was skipped.
Some questions:

1) Why in generic/TkDND_Cursors.c you changed the cursor checks to NULL, instead of None? According to the manuals, these functions do still return None.

2) Why in unix/TkDND_XDND.c you changed Tk_BackgroundError to Tcl_BackgroundError?

3) What are the dashes in `Tcl_InitStubs(interp, "8.3-", 0)`?

**Comment by PaulObermeier** [comment]
Hi Georgios,

Starting point of my porting attempts was tag tkdnd-release-test-v2.9.3.
I updated the version number to 2.9.4 to distinguish the new version.

Regarding your other questions:
1. **None** gives compile errors on Windows using gcc:
```
generic/TkDND_Cursors.c: In function 'Tk_Cursor_* TkDND_GetCursor(Tcl_Interp*, Tcl_Obj*)':
generic/TkDND_Cursors.c:91:14: error: no match for 'operator==' 
(operand types are 'Tk_Cursor {aka Tk_Cursor_*}' and <unnamed enum>)
   if (cursor == None) {
```

2. In Tk 8.7 the following macro was available:
`#define Tk_BackgroundError	Tcl_BackgroundError`
In Tk 9 Tk_BackgroundError was removed completely.

3. The dash indicates support for 8.5 and newer.

Note, that I only ported and tested the following events on Windows: DND_Text, DND_Files.

Regarding the needed changes to support both Tcl/Tk 8 and 9, you might find the following pages useful:
https://core.tcl-lang.org/tcl/wiki?name=Migrating%20C%20extensions%20to%20Tcl%209
https://core.tcl-lang.org/tcl/wiki?name=Migrating%20scripts%20to%20Tcl%209

Paul

**Comment by petasis** [comment]
I have restored the travis ci functionality, and it seems the new version builds under linux, windows, and macos...

**Comment by sl1200mk2** [comment]
Hi,
except the usual deprecation warnings, new code builds and run fine on macOS:

/usr/bin/clang -DPACKAGE_NAME=\"tkdnd\" -DPACKAGE_TARNAME=\"tkdnd\" -DPACKAGE_VERSION=\"2.9.4\" -DPACKAGE_STRING=\"tkdnd\ 2.9.4\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DBUILD_tkdnd=/\*\*/ -DMAC_OSX_TK=1 -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_LIMITS_H=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DTCL_THREADS=1 -DUSE_TCL_STUBS=1 -DUSE_TCLOO_STUBS=1 -DUSE_TK_STUBS=1 -DMODULE_SCOPE=extern\ __attribute__\(\(__visibility__\(\"hidden\"\)\)\) -DHAVE_HIDDEN=1 -DHAVE_CAST_TO_UNION=1 -DHAVE_STDBOOL_H=1 -DTCL_WIDE_INT_IS_LONG=1 -DTCL_CFG_OPTIMIZED=1 -DUSE_TCL_STUBS=1 -DUSE_TK_STUBS=1 -DMAC_TK_COCOA -std=gnu99 -x objective-c -fobjc-arc -I generic -I"/Users/nico/daylight/lib/framework9/build/tcl/Tcl.framework/Versions/9.0/Headers" -I"/Users/nico/daylight/lib/framework9/build/tk/Tk.framework/Versions/9.0/Headers" -I"/Users/nico/daylight/lib/framework9/build/tk/Tk.framework/Versions/9.0/PrivateHeaders" -I"/Users/nico/daylight/lib/frameWork9/customTk/generic" -I"/Users/nico/daylight/lib/frameWork9/customTk/unix" -I"/Users/nico/daylight/lib/frameWork9/customTk/generic/ttk" -I""/Users/nico/daylight/lib/frameWork9/customTk/xlib"" -I"/Users/nico/daylight/lib/frameWork9/customTk/macosx"     -pipe  -Os -DNDEBUG -Wall -fno-common  -mmacosx-version-min=10.15  -c `echo ./macosx/macdnd.m` -o macdnd.o
./macosx/macdnd.m:463:48: warning: 'NSFilenamesPboardType' is deprecated: first deprecated in macOS 10.14 - Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead [-Wdeprecated-declarations]
  if ([[sourcePasteBoard types] containsObject:NSFilenamesPboardType]) {
                                               ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:312:32: note: 'NSFilenamesPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSFilenamesPboardType API_DEPRECATED("Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:641:38: warning: 'NSFilenamesPboardType' is deprecated: first deprecated in macOS 10.14 - Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead [-Wdeprecated-declarations]
    } else if ([type isEqualToString:NSFilenamesPboardType]) {
                                     ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:312:32: note: 'NSFilenamesPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSFilenamesPboardType API_DEPRECATED("Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:399:62: warning: 'NSPasteboardTypeFindPanelSearchOptions' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSPasteboardTypeFindPanelSearchOptions: {str = NSPasteboardTypeFindPanelSearchOptions; break;}
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                             NSPasteboardTypeTextFinderOptions
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:332:38: note: 'NSPasteboardTypeFindPanelSearchOptions' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType const NSPasteboardTypeFindPanelSearchOptions API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeTextFinderOptions", macos(10.6,10.14));
                                     ^
./macosx/macdnd.m:400:62: warning: 'NSStringPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSStringPboardType:                     {str = NSStringPboardType                    ; break;}
                                                             ^~~~~~~~~~~~~~~~~~
                                                             NSPasteboardTypeString
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:311:32: note: 'NSStringPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSStringPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeString", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:401:62: warning: 'NSFilenamesPboardType' is deprecated: first deprecated in macOS 10.14 - Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead [-Wdeprecated-declarations]
    case TYPE_NSFilenamesPboardType:                  {str = NSFilenamesPboardType                 ; break;}
                                                             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:312:32: note: 'NSFilenamesPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSFilenamesPboardType API_DEPRECATED("Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:402:62: warning: 'NSPostScriptPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSPostScriptPboardType:                 {str = NSPostScriptPboardType                ; break;}
                                                             ^~~~~~~~~~~~~~~~~~~~~~
                                                             @"com.adobe.encapsulated-postscript"
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:325:32: note: 'NSPostScriptPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSPostScriptPboardType API_DEPRECATED_WITH_REPLACEMENT("@\"com.adobe.encapsulated-postscript\"", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:403:62: warning: 'NSTIFFPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSTIFFPboardType:                       {str = NSTIFFPboardType                      ; break;}
                                                             ^~~~~~~~~~~~~~~~
                                                             NSPasteboardTypeTIFF
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:313:32: note: 'NSTIFFPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSTIFFPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeTIFF", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:404:62: warning: 'NSRTFPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSRTFPboardType:                        {str = NSRTFPboardType                       ; break;}
                                                             ^~~~~~~~~~~~~~~
                                                             NSPasteboardTypeRTF
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:314:32: note: 'NSRTFPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSRTFPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeRTF", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:405:62: warning: 'NSTabularTextPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSTabularTextPboardType:                {str = NSTabularTextPboardType               ; break;}
                                                             ^~~~~~~~~~~~~~~~~~~~~~~
                                                             NSPasteboardTypeTabularText
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:315:32: note: 'NSTabularTextPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSTabularTextPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeTabularText", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:406:62: warning: 'NSFontPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSFontPboardType:                       {str = NSFontPboardType                      ; break;}
                                                             ^~~~~~~~~~~~~~~~
                                                             NSPasteboardTypeFont
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:316:32: note: 'NSFontPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSFontPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeFont", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:407:62: warning: 'NSRulerPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSRulerPboardType:                      {str = NSRulerPboardType                     ; break;}
                                                             ^~~~~~~~~~~~~~~~~
                                                             NSPasteboardTypeRuler
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:317:32: note: 'NSRulerPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSRulerPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeRuler", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:409:62: warning: 'NSColorPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSColorPboardType:                      {str = NSColorPboardType                     ; break;}
                                                             ^~~~~~~~~~~~~~~~~
                                                             NSPasteboardTypeColor
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:318:32: note: 'NSColorPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSColorPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeColor", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:410:62: warning: 'NSRTFDPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSRTFDPboardType:                       {str = NSRTFDPboardType                      ; break;}
                                                             ^~~~~~~~~~~~~~~~
                                                             NSPasteboardTypeRTFD
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:319:32: note: 'NSRTFDPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSRTFDPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeRTFD", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:411:62: warning: 'NSHTMLPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSHTMLPboardType:                       {str = NSHTMLPboardType                      ; break;}
                                                             ^~~~~~~~~~~~~~~~
                                                             NSPasteboardTypeHTML
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:320:32: note: 'NSHTMLPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSHTMLPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeHTML", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:412:62: warning: 'NSURLPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSURLPboardType:                        {str = NSURLPboardType                       ; break;}
                                                             ^~~~~~~~~~~~~~~
                                                             NSPasteboardTypeURL
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:321:32: note: 'NSURLPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSURLPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeURL", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:413:62: warning: 'NSPDFPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSPDFPboardType:                        {str = NSPDFPboardType                       ; break;}
                                                             ^~~~~~~~~~~~~~~
                                                             NSPasteboardTypePDF
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:322:32: note: 'NSPDFPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSPDFPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypePDF", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:414:62: warning: 'NSVCardPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSVCardPboardType:                      {str = NSVCardPboardType                     ; break;}
                                                             ^~~~~~~~~~~~~~~~~
                                                             kUTTypeVCard
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:326:32: note: 'NSVCardPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSVCardPboardType API_DEPRECATED_WITH_REPLACEMENT("kUTTypeVCard", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:415:62: warning: 'NSFilesPromisePboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSFilesPromisePboardType:               {str = NSFilesPromisePboardType              ; break;}
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~
                                                             kPasteboardTypeFileURLPromise
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:330:32: note: 'NSFilesPromisePboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSFilesPromisePboardType API_DEPRECATED_WITH_REPLACEMENT("kPasteboardTypeFileURLPromise", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:416:62: warning: 'NSMultipleTextSelectionPboardType' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
    case TYPE_NSMultipleTextSelectionPboardType:      {str = NSMultipleTextSelectionPboardType     ; break;}
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                             NSPasteboardTypeMultipleTextSelection
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:323:32: note: 'NSMultipleTextSelectionPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSMultipleTextSelectionPboardType API_DEPRECATED_WITH_REPLACEMENT("NSPasteboardTypeMultipleTextSelection", macos(10.5,10.14));
                               ^
./macosx/macdnd.m:772:21: warning: variable 'actions' set but not used [-Wunused-but-set-variable]
  int               actions = 0;
                    ^
./macosx/macdnd.m:1306:34: warning: 'NSFilenamesPboardType' is deprecated: first deprecated in macOS 10.14 - Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead [-Wdeprecated-declarations]
        [draggedtypes addObject: NSFilenamesPboardType];
                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:312:32: note: 'NSFilenamesPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSFilenamesPboardType API_DEPRECATED("Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead", macos(10.0,10.14));
                               ^
./macosx/macdnd.m:1325:34: warning: 'NSFilenamesPboardType' is deprecated: first deprecated in macOS 10.14 - Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead [-Wdeprecated-declarations]
        [draggedtypes addObject: NSFilenamesPboardType];
                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:312:32: note: 'NSFilenamesPboardType' has been explicitly marked deprecated here
APPKIT_EXTERN NSPasteboardType NSFilenamesPboardType API_DEPRECATED("Create multiple pasteboard items with NSPasteboardTypeFileURL or kUTTypeFileURL instead", macos(10.0,10.14));
                               ^
22 warnings generated.

++

**Comment by petasis** [comment]
You have used configure or cmake for your build?

I see that configure picks gcc: https://app.travis-ci.com/github/petasis/tkdnd/jobs/615600316

**Comment by sl1200mk2** [comment]
Hi Georgios,
I've used configure but I do export CC=/usr/bin/clang before compilation.
I think that native way to compile on macOS is to use AppleClang and /usr/bin/gcc points to AppleClang
nico@love ~ % /usr/bin/gcc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

++

**Comment by petasis** [comment]
I have ran "Ventura 13.6.3" in docker, and I have tried to fix the deprecated functions (changes committed).
It seems to work in this macOS version, after the fixes.

**Comment by sl1200mk2** [comment]
wow, cool !!
I've tested on macOS 12 and there's only one warning left:
/usr/bin/clang -DPACKAGE_NAME=\"tkdnd\" -DPACKAGE_TARNAME=\"tkdnd\" -DPACKAGE_VERSION=\"2.9.4\" -DPACKAGE_STRING=\"tkdnd\ 2.9.4\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DBUILD_tkdnd=/\*\*/ -DMAC_OSX_TK=1 -DHAVE_STDIO_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_STRINGS_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_UNISTD_H=1 -DSTDC_HEADERS=1 -DHAVE_LIMITS_H=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DTCL_THREADS=1 -DUSE_TCL_STUBS=1 -DUSE_TCLOO_STUBS=1 -DUSE_TK_STUBS=1 -DMODULE_SCOPE=extern\ __attribute__\(\(__visibility__\(\"hidden\"\)\)\) -DHAVE_HIDDEN=1 -DHAVE_CAST_TO_UNION=1 -DHAVE_STDBOOL_H=1 -DTCL_WIDE_INT_IS_LONG=1 -DTCL_CFG_OPTIMIZED=1 -DUSE_TCL_STUBS=1 -DUSE_TK_STUBS=1 -DMAC_TK_COCOA -std=gnu99 -x objective-c -fobjc-arc -I generic -I"/Users/nico/daylight/lib/framework9/build/tcl/Tcl.framework/Versions/9.0/Headers" -I"/Users/nico/daylight/lib/framework9/build/tk/Tk.framework/Versions/9.0/Headers" -I"/Users/nico/daylight/lib/framework9/build/tk/Tk.framework/Versions/9.0/PrivateHeaders" -I"/Users/nico/daylight/lib/frameWork9/customTk/generic" -I"/Users/nico/daylight/lib/frameWork9/customTk/unix" -I"/Users/nico/daylight/lib/frameWork9/customTk/generic/ttk" -I""/Users/nico/daylight/lib/frameWork9/customTk/xlib"" -I"/Users/nico/daylight/lib/frameWork9/customTk/macosx"     -pipe  -Os -DNDEBUG -Wall -fno-common  -mmacosx-version-min=10.15  -c `echo ./macosx/macdnd.m` -o macdnd.o
./macosx/macdnd.m:848:21: warning: variable 'actions' set but not used [-Wunused-but-set-variable]
  int               actions = 0;
                    ^
1 warning generated.


I've tested within my app (which only dnd text) and it works fine (against Tcl9&&Tk9).
many thanks,
++

**Comment by petasis** [comment]
Yes, I know about this warning. I do not if there is a way to limit the available actions by a drag source is macOS.
This variable gets defined, but never used.

**Comment by sl1200mk2** [comment]
in configure.ac at line 177 the -framework Carbon is not needed anymore

++

**Comment by petasis** [comment]
It seems it is needed for earlier versions:

https://app.travis-ci.com/github/petasis/tkdnd/jobs/615685007

**Comment by petasis** [comment]
Ok, I think we should close this issue.
